Prevent undefined method errors when include is provided (#1)
What?
- Default to an empty hash when fetching relationships for a serializer class that does not have any relationships defined.

Why?
- Previously, if `include` is passed in as argument for a serializer that does not have relationships defined, then a: `undefined method [] for nil:NilClass` is raised rather than the expected `JSONAPI::Serializer::UnsupportedIncludeError`. This was because `Serializer#relationships_to_serialize` was returning `nil`.

What is the current behavior?
- When `include` is provided as an argument for a serializer that does not have any relationships defined, then an `undefined method [] for nil:NilClass` error is raised instead of the expected: `JSONAPI::Serializer::UnsupportedIncludeError`.
```ruby
u = User.fake
UserSerializer.new(user, include: ['bad_include']) # => <NoMethodError: undefined method `[]' for nil:NilClass>
```

What is the new behavior?
- When `include` is provided as an argument for a serializer that does not have any relationships defined, then `JSONAPI::Serializer::UnsupportedIncludeError` is returned:
```ruby
u = User.fake
UserSerializer.new(user, include: ['bad_include']) # => <JSONAPI::Serializer::UnsupportedIncludeError>
```

Notes
- We've forked this repo, so that we can use the fix in: https://github.com/thrivadev/jsonapi-serializer/pull/1, while we wait for https://github.com/jsonapi-serializer/jsonapi-serializer/pull/236 being merged.